export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_FEATURED_PRODUCTS_SUCCESS = 'FETCH_FEATURED_PRODUCTS_SUCCESS';
export const FETCH_BANNERS_SUCCESS = 'FETCH_BANNERS_SUCCESS';
export const FETCH_FOOTER_SUCCESS = 'FETCH_FOOTER_SUCCESS';
export const FETCH_PRODUCTS_CATEGORIES_SUCCESS = 'FETCH_PRODUCTS_CATEGORIES_SUCCESS';
export const FETCH_PRODUCTS_MENU_SUCCESS = 'FETCH_PRODUCTS_MENU_SUCCESS';
export const FETCH_PRODUCTS_CATEGORIES_BY_TAG_SUCCESS = 'FETCH_PRODUCTS_CATEGORIES_BY_TAG_SUCCESS';
export const FETCH_WHY_CHOOSE_US_SUCCESS = 'FETCH_WHY_CHOOSE_US_SUCCESS';
export const FETCH_OFFER_OF_THE_DAY_SUCCESS = 'FETCH_OFFER_OF_THE_DAY_SUCCESS';
export const FETCH_FULL_PRODUCTS_CATEGORIES_SUCCESS = 'FETCH_FULL_PRODUCTS_CATEGORIES_SUCCESS';
export const FETCH_PRODUCTS_BY_CATEGORY_SUCCESS = 'FETCH_PRODUCTS_BY_CATEGORY_SUCCESS';
export const FETCH_PRODUCTS_BY_SUB_CATEGORY_SUCCESS = 'FETCH_PRODUCTS_BY_SUB_CATEGORY_SUCCESS';

//navigation ones
export const NAVIGATION_CHANGE = "NAVIGATION_CHANGE";

// sales ones
export const SELECTED_PRODUCT_CATEGORY = 'SELECTED_PRODUCT_CATEGORY';
export const FETCH_BEST_SELLERS_PRODUCTS_SUCCESS = 'FETCH_BEST_SELLERS_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_TYPES_SUCCESS = 'FETCH_PRODUCTS_TYPES_SUCCESS';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const SELECTED_PRODUCT_TYPE_FILTER = 'SELECTED_PRODUCT_TYPE_FILTER';
export const REMOVE_PRODUCT_FROM_SHOPPING_CART = 'REMOVE_PRODUCT_FROM_SHOPPING_CART';
export const GET_TOTAL = 'GET_TOTAL';

// login ones
export const SAVE_USER = 'SAVE_USER';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const LOGIN_FROM_CHECKOUT = 'LOGIN_FROM_CHECKOUT';
